### ISSUE TITLE
Date is not up to date

### ISSUE THREAD

**Issue by SandeepVashishtha** [amanr3207/Lost-and-Found-responsive-website#1]
In LOST form the 'Date Lost' is not up to date it is till DEC'21

![Screenshot 2024-03-03 112510](https://github.com/amanr3207/Lost-and-Found-responsive-website/assets/64915843/39d18f88-14c0-4487-944e-f55be13e9b74)

**Comment by amanr3207** [comment]
Done... Now check it

**Comment by SandeepVashishtha** [comment]
check my pull request
